name: Gatsby build and tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 16
        uses: actions/setup-node@v1
        with:
          node-version: '16.13.x'
          cache: 'npm'
      - name: Remove old node_modules
        working-directory: ./app
        run: rm -rf node_modules/    
      - name: Install dependencies
        working-directory: ./app
        run: npm install
      - name: Run unit and integration tests
        working-directory: ./app
        run: npm run test
      - name: Run build
        working-directory: ./app
        run: npm run build